d2qc/d2qc/data/urls.py
from django.urls import path, register_converter
from django.conf.urls import include

from . import views
from d2qc.data.views import *
from d2qc.data.models import *
from d2qc.urlconverters import *
from rest_framework import routers, serializers, viewsets

# Routers provide an easy way of automatically determining the URL conf.
router = routers.DefaultRouter()
router.register(r'set', DataSetViewSet)
router.register(r'nested/set', NestedDataSetViewSet)
router.register(r'type', DataTypeViewSet)
router.register(r'station', StationViewSet)
router.register(r'cast', CastViewSet)
router.register(r'dept', DepthViewSet)
router.register(r'value', DataValueViewSet)
router.register(r'unit', DataUnitViewSet)
router.register(r'file', DataFileViewSet)

register_converter(DataTypeConverter, 'datatypes')
register_converter(LatLonBoundsConverter, 'bounds')
register_converter(NumberListConverter, 'numbers')

px = 'join/dataset'
cx = 'crossover'
ids = '/<numbers:data_set_ids>'
id = '/<int:data_set_id>'
types = '/<datatypes:types>'
bounds = '/<bounds:bounds>'
min_depth = '/<int:min_depth>'
max_depth = '/<int:max_depth>'
file = 'data_file'
add = '/add/'
detail = '/detail'
update = '/update'
import_ = '/import'
delete = '/delete'
merge = '/merge'
normalize = '/normalize'
operations = 'operations/'
data_set = 'data_set'
profile = 'profile'
parameter = 'parameter'
crossover = 'crossover'
urlpatterns = [
    path(px + ids, views.dataSet),
    path(px + ids + types, views.dataSet),
    path(px + ids + types + bounds, views.dataSet),
    path(px + ids + types + bounds + min_depth, views.dataSet),
    path(px + ids + types + bounds + min_depth + max_depth, views.dataSet),
    path(px + ids + types + min_depth, views.dataSet),
    path(px + ids + types + min_depth + max_depth, views.dataSet),
    path(cx + id + types, views.crossover),
    path(data_set + detail + '/<int:pk>/' + parameter + '/get_summary_statistics_status/<cache_key_px>', views.data_set.get_summary_statistics_status, name='get_summary_statistics_status'),
    path(data_set + detail + '/<int:pk>/' + parameter + '/<int:parameter_id>/'+ crossover + '/get_summary_statistics_status/<cache_key_px>', views.data_set.get_summary_statistics_status, name='get_summary_statistics_status'),
    path(file + detail + '/<int:pk>/' + 'import_status', views.data_file.import_status_pre_import, name='import_status_pre_import'),
    path(file + detail + '/<int:pk>' + import_ + '/import_status', views.data_file.import_status_post_import, name='import_status_post_import'),

    path(
            file + detail + '/<int:pk>/',
            DataFileDetail.as_view(),
            name='data_file-detail'
    ),
    path(
            file + update + '/<int:pk>/',
            DataFileUpdate.as_view(),
            name='data_file-update'
    ),
    path(
            file + detail + '/<int:pk>' + import_,
            DataFileDetail.as_view(),
            name='data_file-import'
    ),
    path(
            file + detail + '/<int:pk>' + import_ + '/exec',
            DataFileDetail.as_view(exec=True),
            name='data_file-import-exec'
    ),
    path(
            file + '/',
            DataFileList.as_view(),
            name='data_file-list'
    ),
    path(
            file + add,
            DataFileCreate.as_view(),
            name='data_file-create'
    ),
    path(
            file + delete + '/<int:pk>',
            DataFileDelete.as_view(),
            name='data_file-delete'
    ),
    path(
            data_set + '/',
            DataSetList.as_view(),
            name='data_set-list'
    ),
    path(
            data_set + detail + '/<int:pk>',
            DataSetDetail.as_view(),
            name='data_set-detail'
    ),
    path(
        data_set + detail + '/<int:pk>/'
                + parameter + '/<int:parameter_id>',
        DataSetDetail.as_view(),
        name='data_set_parameter-detail'
    ),
    path(
        data_set + detail + '/<int:pk>/'
                + parameter + '/<int:parameter_id>/'
                + crossover + '/<int:data_set_id>',
        DataSetDetail.as_view(),
        name='data_set_crossover'
    ),
    path(
        data_set + merge + '/<int:pk>/',
        DataSetMerge.as_view(),
        name='data_set_merge'
    ),
    path(
        data_set + normalize + '/<int:pk>/',
        DataSetNormalization.as_view(),
        name='data_set_normalize'
    ),
    path(
        data_set + detail + '/<int:pk>/' + operations,
        OperationList.as_view(),
        name='data_set_operations'
    ),
    path(
            data_set + delete + '/<int:pk>',
            DataSetDelete.as_view(),
            name='data_set-delete'
    ),
    path(
            '',
            IndexPage.as_view(),
            name='data'
    ),
    path(
            profile + update,
            ProfileUpdate.as_view(),
            name='profile-update'
    ),
]

d2qc/d2qc/urls.py
from django.contrib import admin
from django.urls import include, path, reverse_lazy, re_path
from django.views.generic import RedirectView



# Wire up our API using automatic URL routing.
# Additionally, we include login URLs for the browsable API.
urlpatterns = [
    path('admin/', admin.site.urls),
    path('mockup/', include('d2qc.mockup.urls')),
    re_path(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),

    path('data/', include('d2qc.data.urls')),
    path('account/', include('d2qc.account.urls')),
    path('account/', include('django.contrib.auth.urls')),
    path('', RedirectView.as_view(permanent=False, url=reverse_lazy('data'))),

]

d2qc/d2qc/data/models/offset_type.py
from django.contrib.gis.db import models

class OffsetType(models.Model):
    class Meta:
        db_table = 'd2qc_offset_types'
    id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=20, default='', blank=True)
    description = models.CharField(max_length=255, default='', blank=True)
    def __str__(self):
        return self.name

d2qc/d2qc/data/forms.py
from django.forms import ModelForm, FileInput
from d2qc.data.models import DataFile
from django.core.exceptions import ValidationError


class DataFileForm(ModelForm):
    class Meta:
        model = DataFile
        fields = ['filepath', 'name', 'description']
        widgets = {
            "filepath": FileInput(
                attrs={
                    'onchange':
                    """
                        var filename = '';
                        if (this.files.length > 0) {
                            filename = this.files[0].name;
                        }

                        document.getElementById('id_name').value = filename;
                    """
                })
        }
    def __init__(self, *args, **kwargs):
        self.user = kwargs.pop('user', None)
        super(DataFileForm, self).__init__(*args, **kwargs)


    def clean_filepath(self):
        for chunk in self.cleaned_data['filepath'].chunks():
            try:
                chunk = chunk.decode('iso-8859-1')
            except:
                try:
                    chunk = chunk.decode('utf-8')
                except Exception as e:
                    raise ValidationError(
                        'Character encoding not in (utf-8, iso-8859-1)'
                    )
            break
        return self.cleaned_data['filepath']

    def clean_name(self):
        user_has_file = DataFile.objects.filter(
            name=self.cleaned_data['name'],
            owner=self.user,
        ).exists()
        if user_has_file:
            ok = False
            raise ValidationError(
                    "Name exists: '{}'. Try a different name.".format(
                        self.cleaned_data['name'],
                    ),
            )
        return self.cleaned_data['name']

d2qc/d2qc/data/forms/data_file.py
from django.forms import ModelForm, FileInput
from d2qc.data.models import DataFile
from django.core.exceptions import ValidationError


class DataFileForm(ModelForm):
    class Meta:
        model = DataFile
        fields = ['filepath', 'name', 'description']
        widgets = {
            "filepath": FileInput(
                attrs={
                    'onchange':
                    """
                        var filename = '';
                        if (this.files.length > 0) {
                            filename = this.files[0].name;
                        }

                        document.getElementById('id_name').value = filename;
                    """
                })
        }
    def __init__(self, *args, **kwargs):
        self.user = kwargs.pop('user', None)
        super(DataFileForm, self).__init__(*args, **kwargs)


    def clean_filepath(self):
        for chunk in self.cleaned_data['filepath'].chunks():
            try:
                chunk = chunk.decode('iso-8859-1')
            except:
                try:
                    chunk = chunk.decode('utf-8')
                except Exception as e:
                    raise ValidationError(
                        'Character encoding not in (utf-8, iso-8859-1)'
                    )
            break
        return self.cleaned_data['filepath']

    def clean_name(self):
        user_has_file = DataFile.objects.filter(
            name=self.cleaned_data['name'],
            owner=self.user,
        ).exists()
        if user_has_file:
            ok = False
            raise ValidationError(
                    "Name exists: '{}'. Try a different name.".format(
                        self.cleaned_data['name'],
                    ),
            )
        return self.cleaned_data['name']

d2qc/d2qc/data/forms/merge.py
from django import forms
from d2qc.data.models import DataTypeName, DataValue, Depth, DataSet
from d2qc.data.models import Operation, OperationType
import pandas as pd
import numpy as np
import glodap.util.stats as stats
import copy
from django.core.cache import cache

class MergeForm(forms.Form):
    _cache_name = "merge_form"
    INITIAL_MERGE_TYPE = 1
    INITIAL_MERGE_MIN_DEPTH = 0
    merge_type = forms.ChoiceField(
        label = "Merge type action",
        choices=[
            (1, "1 - Do not merge"),
            (2, "2 - Merge using only secondary, no primary parameter"),
            (3, "3 - Merge using only primary, no secondary parameter"),
            (4, "4 - Merge using primary (few or no secondary or primary>80%)."),
            (5, "5 - Merge using mean of primary and UNCHANGED secondary."),
            (6, "6 - Merge using mean of primary and fitted secondary."),
            (7, "7 - Merge using primary because bad fit of secondary."),
        ],
        initial = INITIAL_MERGE_TYPE,
    )
    merge_min_depth = forms.IntegerField(
        initial = INITIAL_MERGE_MIN_DEPTH,
        min_value = 0,
        required = True,
        label = "Minimum depth used to calculate linear fit",
        widget = forms.TextInput,
    )

    def __init__(self, *args, **kwargs):
        try:
            data_type_names = kwargs.pop('data_type_names')
        except KeyError:
            data_type_names = None
        primary_field = None
        secondary_field = None

        if data_type_names:
            primary = int(cache.get(f"{self._cache_name}__primary", 0))
            secondary = int(cache.get(f"{self._cache_name}__secondary", 0))
            merge_min_depth = cache.get(
                f"{self._cache_name}__merge_min_depth",
                self.INITIAL_MERGE_MIN_DEPTH,
            )
            merge_type = cache.get(
                f"{self._cache_name}__merge_type",
                self.INITIAL_MERGE_TYPE,
            )
            # Only use cache data if data types exists in data_type_names
            if (
                    MergeForm.in_data_type_names(
                        primary,
                        secondary,
                        data_type_names,
                    )
            ):
                if len(args) == 0 and not 'data' in kwargs:
                    data = {
                        'primary': primary,
                        'secondary': secondary,
                        'merge_min_depth': merge_min_depth,
                        'merge_type': merge_type,
                    }
                    kwargs['data'] = data
            else:
                primary = None
                secondary = None

            choices = [(t['id'], '') for t in data_type_names]
            primary_field = forms.ChoiceField(
                label = "Pri.",
                widget = forms.RadioSelect,
                choices = choices,
                initial = primary,
            )
            secondary_field = forms.ChoiceField(
                label = "Sec.",
                widget = forms.RadioSelect,
                choices = choices,
                initial = secondary,
            )
        super().__init__(*args, **kwargs)
        self.fields['primary'] = primary_field
        self.fields['secondary'] = secondary_field

    @staticmethod
    def in_data_type_names(primary:int,secondary:int,data_type_names:list=[]):
        """
        return true if primary and secondary are found both found in
        data_type_names id. data_type_names is an array of dicts with an
        id property: data_type_names=[{'id':1},{'id':2},...]
        """
        p = 0
        s = 0
        for d in data_type_names:
            if int(d['id']) == int(primary):
                p = 1
            if int(d['id']) == int(secondary):
                s = 1
        return s + p == 2

    def is_valid(self):
        retval = super().is_valid()
        if retval:
            cache.set(
                f"{self._cache_name}__primary",
                self.cleaned_data['primary']
            )
            cache.set(
                f"{self._cache_name}__secondary",
                self.cleaned_data['secondary']
            )
            cache.set(
                f"{self._cache_name}__merge_min_depth",
                self.cleaned_data['merge_min_depth']
            )
            cache.set(
                f"{self._cache_name}__merge_type",
                self.cleaned_data['merge_type']
            )
        return retval

    def save_merge_data(self, data_set):
        primary = DataTypeName.objects.get(pk=self.cleaned_data['primary'])
        secondary = DataTypeName.objects.get(pk=self.cleaned_data['secondary'])
        name = "{}#{}_{}".format(
            self.cleaned_data['merge_type'],
            primary.name,
            secondary.name,
        )
        data = data_set.get_merge_data(
            self.cleaned_data['primary'],
            self.cleaned_data['secondary'],
            min_depth = self.cleaned_data['merge_min_depth'],
        )

        operation_type = OperationType.objects.filter(name='merge').first()

        if DataTypeName.objects.filter(name=name).exists():
            data_type_name = DataTypeName.objects.filter(name=name).first()
        else:
            data_type_name = copy.copy(primary)
            data_type_name.id = None
            data_type_name.name = name
            data_type_name.operation_type = operation_type
            data_type_name.save()

        merge_type = int(self.cleaned_data['merge_type'])
        slope, intercept = stats.linear_fit(
            data['primary'].tolist(),
            data['secondary'].tolist(),
        )
        if merge_type == 6:
            data['secondary'] = (data['secondary'] - intercept) / slope

        new_values = []
        for i, row in data.iterrows():
            value = DataValue(qc_flag=2,data_type_name=data_type_name)
            value.depth_id = row['depth_id']
            value.value = np.nan
            if merge_type in [2, 3, 4, 7]:
                name = 'secondary' if merge_type == 2 else 'primary'
                value.value = row[name]
            elif merge_type in [5, 6]:
                value.value = np.nanmean([row['primary'], row['secondary']])

            if not np.isnan(value.value):
                new_values.append(value)
        DataValue.objects.bulk_create(new_values)

        # Update operations table if successful
        operation = Operation(
            operation_type = operation_type,
            data_type_name = data_type_name,
            data_set = data_set,
            name = f"{primary.name} vs {secondary.name}, type #{merge_type}",
            data = {
                'merge_type': merge_type,
                'primary': {
                    'name': primary.name,
                    'id': primary.id,
                },
                'secondary': {
                    'name': secondary.name,
                    'id': secondary.id,
                },
            }
        )
        operation.save()
        data_set.set_type_list(None)

d2qc/d2qc/data/forms/profile.py
from django.forms import ModelForm, RadioSelect
from d2qc.data.models import Profile

class ProfileForm(ModelForm):
    class Meta:
        model = Profile
        fields = [
            'min_depth',
            'crossover_radius',
            'depth_metric',
            'only_qc_controlled_data',
        ]
        widgets = {
            'depth_metric': RadioSelect(attrs={'cols': 80, 'rows': 20}),
        }

class MergeProfileForm(ProfileForm):
    class Meta:
        model = Profile
        fields = [
            'only_qc_controlled_data',
        ]

class DataSetDetailsProfileForm(ProfileForm):
    class Meta:
        model = Profile
        fields = [
            'min_depth',
            'crossover_radius',
            'depth_metric',
            'only_qc_controlled_data',
        ]
        widgets = {
            'depth_metric': RadioSelect(attrs={'cols': 80, 'rows': 20}),
        }

d2qc/d2qc/data/views/cast.py
from rest_framework import viewsets

from d2qc.data.models import Cast
from d2qc.data.serializers import CastSerializer


class CastViewSet(viewsets.ModelViewSet):

    queryset = Cast.objects.all()
    serializer_class = CastSerializer

d2qc/d2qc/data/templates/data/datafile_confirm_delete.html
{% extends "base.html" %}
{% block content %}
<form method="post">
    {% csrf_token %}
    <h3>Are you sure you want to delete "{{ object }}"?</h3>
    <input type="submit" value="Confirm">
</form>
{% endblock %}

d2qc/d2qc/data/templates/data/datafile_detail.html
{% extends "base.html" %}
{% block content %}
<style>
.message {
  color: red;
}
</style>
<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js" type="text/javascript"></script>
<script>
  $.get('import_status', {file_id: {{object.id}}},function(data){
  $('#import_status').html('<h4>' + data + '</h4>');
  });

  var counter = 1;
  const interval = setInterval(function() {
    $.get('import_status',function(data){

      if (data.includes('Import in progress')){
        data = data + ' .'.repeat(counter);
      }

      $('#import_status').html('<h4>' + data + '</h4>');

      if (data.substring(0, 8) === 'Imported') {
        clearInterval(interval);
      }
      if (data.substring(0,17) === 'File not imported'){
        clearInterval(interval);
      }

      if (data.includes("Encountered:")){
        clearInterval(interval);
      }

      counter++;
      counter = counter > 3 ? 1 : counter;
    });  
  }, 2000);
    
  
</script>


    <div>
        <h3>
            ID: {{ object.id }} -
            {% if object.name %}
            {{ object.name }}
            {% else %}
            {{ object.filepath }}
            {% endif %}
        </h3>
        <div id = 'import_status' class='import'>       
        </div>
        <div class="import">
        <dl>
            <dt>Filepath</dt>
            <dd>{{ object.filepath }}</dd>
            <dt>Owner</dt>
            <dd>(user: {{ owner.username }})</dd>
            <dd>{{ owner.first_name }} {{ owner.last_name }}</dd>
            {% if object.description %}
            <dt>Description</dt>
            <dd>{{ object.description }}</dd>
            {% endif %}
            <dt>Header</dt>
            <dd>{{ object.headers | linebreaks }}</dd>
            <dt>Line count</dt>
            <dd>{{ count }}</dd>

        </dl>
        <a href="{% url 'data_file-update' object.id %}">[Edit]</a>
        {% if not object.import_finnished %}
        <a href="{% url 'data_file-import-exec' object.id %}">[Import file]</a>
        {% endif %}
        <a href="{% url 'data_file-delete' object.id %}">[Delete]</a>
        {% if filehead and not object.import_finnished %}
        <div class="scrollable">
            <h3>First lines of file</h3>
            <p>
                {% for line in filehead %}
                    {{ line }}<br/>
                {% endfor %}
            </p>
        </div>
        {% endif %}
    </div>
{% endblock %}

d2qc/d2qc/data/templates/data/datafile_form.html
{% extends "base.html" %}
{% block content %}
<h1>Upload data file</h1>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_ul }}
        <input type="submit" value="Save" />
    </form>
{% endblock %}

d2qc/d2qc/data/templates/data/datafile_list.html
{% extends "base.html" %}
{% block content %}
    <h3>Your data files</h3>
    <p>Below are the data files.
        <a href="{%url 'data_file-create'%}">Upload more files</a>
    </p>
    {% if object_list %}
        <ul>
        {% for obj in object_list %}
            <li>
                <a href="{% url 'data_file-detail' obj.id %}">{{ obj.name }}</a>
                <a href="{% url 'data_file-delete' obj.id %}">[Delete file]</a>
                {% if not obj.import_started %}
                    <a href="{% url 'data_file-import' obj.id %}">
                        [Import file]
                    </a>
                {% endif %}
            </li>
        {% endfor %}
        </ul>
    {% else %}
        <p>No crossovers available</p>
    {% endif %}
{% endblock %}

d2qc/d2qc/data/templates/data/dataset_confirm_delete.html
{% extends "base.html" %}
{% block content %}
<form method="post">
    {% csrf_token %}
    <h3>Are you sure you want to delete "{{ object }}"?</h3>
    <input type="submit" value="Confirm">
</form>
{% endblock %}

d2qc/d2qc/data/templates/data/dataset_detail.html
{% extends "base.html" %}
{% block dataset_detail_menu %}
<ul><li>
    <a
    id="data_set-detail"
    href="{% url 'data_set-detail' object.id %}"
    >
        {{ object.expocode }}
    </a>
    <ul>
        <li>
            <a
                id="data_set_merge"
                href="{% url 'data_set_merge' object.id %}"
            >
                Merge data
            </a>
        </li>
        {% if is_normalizable %}
        <li>
            <a
                id="data_set_normalize"
                href="{% url 'data_set_normalize' object.id %}"
            >
                Normalize
            </a>
        </li>
        {% endif %}
        {% if has_operations %}
        <li>
            <a
                id="data_set_operations"
                href="{% url 'data_set_operations' object.id %}"
            >
                Operations
            </a>
        </li>
        {% endif %}
    </ul>
</li></ul>
{% endblock %}

d2qc/d2qc/data/templates/data/dataset_list.html
{% extends "base.html" %}
{% block content %}
    <h3>Your data sets</h3>
    <p>Below are the data sets.</p>
    {% if object_list %}
        <ul>
        {% for obj in object_list %}
            <li>{{ obj.expocode }}
                <a href="{% url 'data_set-detail' obj.id %}">{{ obj.expocode }}</a>
                <a href="{% url 'data_set-delete' obj.id %}">[Delete data set]</a>
            </li>
        {% endfor %}
        </ul>
    {% else %}
        <p>No crossovers available</p>
    {% endif %}
{% endblock %}

d2qc/d2qc/data/templates/data/dataset_merge.html
{% extends "base.html" %}
{% block css %}
{% load mathfilters %}
<link rel="stylesheet" type="text/css"
href="https://cdn.jsdelivr.net/gh/openlayers/openlayers.github.io@master/en/v5.3.0/css/ol.css">
<style>
    #diff_plot, #pri_vs_sec {
        height: 600px;
        width: 600px;
    }

    .outer {
      display: flex;
    }
    .dataset.data{
        display: flex;
        justify-content: flex-start;
        align-items: flex-start;
    }
    .dataset.data td {
        vertical-align: top;
    }
    .dataset-top {
        display: flex;
        justify-content: flex-start;
    }
    .head-wrapper {
      order: 2;
      padding: 10px;
    }
    .map-wrapper {
      order: 1;
      padding: 10px;
    }
    .save {
      display: flex;
      flex-direction: column;

    }
    .save>* {
      margin: 0 0 20px;
    }
    .merge_min_depth input {
      width: 100%;
      box-sizing: border-box;
    }
    .merge_min_depth {
      margin: 10px 0;
    }
</style>
<link rel="stylesheet" href="//cdn.jsdelivr.net/chartist.js/latest/chartist.min.css">
{% endblock %}
{% block js %}
<script src="https://cdn.plot.ly/plotly-latest.min.js"></script>
{% endblock%}
{% block options %}
<aside class="options">
  {% include "util/calculation_options.html" %}
</aside>
{% endblock %}
{% block content %}
<style>
.mergeform {
  display: flex;
  flex-wrap: wrap;
  width: 400px;
  justify-content: center;
}
.mergebutton, .mergeinfo {
  width: 100%
}
.column {
  display: flex;
  width: 80px;
  flex-wrap: wrap;
  justify-content: flex-start;
}
.column h4 {
  width: 100%;
}
.column > * > li{
  display: block;
  height: 25px;
  padding: 0;
  margin: 0;
}
.column input {
  margin: 0;
  padding: 0;
}
.column ul {
  padding: 0 4px;
  margin:0;
  display: block;
  max-width: 100px;
  overflow: hidden;
}
.column fieldset {
  border: none;
}
#id_merge_type {
  max-width: 100%;
  margin: 0 0 10px;
}
</style>
<h3>
  <a href="{% url 'data_set-detail' object.id %}">
    ID: {{ object.id }} - {{ object.expocode }}
  </a>
</h3>
<div class="outer">
  <form class="mergeform" method="post">
    {% csrf_token %}
    <div class="pri column">
      <h4>Primary</h4>
      {{merge_form.primary}}
    </div>
    <div class="sec column">
      <h4>Secondary</h4>
      {{merge_form.secondary}}
    </div>
    {% include "util/data_type_name_list.html" %}
    <div class="mergeinfo">
      <p></p>
    </div>
    <div class="merge_min_depth">
      {{ merge_form.merge_min_depth.label }}:
      {{ merge_form.merge_min_depth }}
    </div>
    <input class="mergebutton" type="submit"
    value="Plot selected parameters" name="plot_parameters"/>
    <h3>Merging</h3>
    <p>To merge the selected parameters, choose the appropriate action from
      the select box below, and click Save merge parameter. This will create
      a new variable in the database named primary_secondary_#, where
    primary is the name of the primary parameter etc, and # is the merge action.</p>
    {{merge_form.merge_type}}

    <input class="mergebutton" type="submit"
    value="Save merge parameter" name="save_parameters"/>
  </form>
  <div id="diff_plot">
  </div>
  <div id="pri_vs_sec">
  </div>
  {% if merge_data %}
  <script type="text/javascript">
    var slope = {{ slope }}
    var intercept = {{ intercept }}
    var merge_data =   JSON.parse('{{ merge_data | escapejs }}');
    var diff = {
      x: merge_data.diff,
      y: merge_data.depth,
      type: 'scatter',
      mode: 'markers'
    }
    var xmax = Math.max(
      Math.abs(Math.max(...merge_data.diff)),
      Math.abs(Math.max(...merge_data.diff))
    );

    var layout = {
        yaxis: {
          autorange: 'reversed',
          rangemode: 'tozero',
          title: {
            text: 'pressure'
          }
        },
        xaxis: {
          range: [-1 * (xmax + (xmax/10)), xmax + (xmax/10)],
          title: {
            text: 'Diff ' + merge_data.primary_type.label + ' minus '
                  + merge_data.secondary_type.label
          }
        },
    };

    Plotly.newPlot('diff_plot', [diff], layout);

    var offset = {
      x: merge_data.primary,
      y: merge_data.secondary,
      type: 'scatter',
      mode: 'markers',
      showlegend: false
    }

    pri_max = Math.max(...merge_data.primary)
    pri_min = Math.min(...merge_data.primary)
    var fit = {
      x: [pri_min, pri_max],
      y: [intercept + pri_min * slope, intercept + pri_max * slope ],
      type: 'scatter',
      mode: 'lines',
      line: {
        color: 'rgb(255,0,0)'
      },
      name: 'Linear fit'
    }
    fit_equation = 'y = ' + slope.toPrecision(5)
    fit_equation += ' * x + ' + intercept.toPrecision(5)
    var title = merge_data.primary_type.label
    title += " vs " + merge_data.secondary_type.label
    title += ": " + fit_equation
    var layout2 = {
      xaxis: {title: {text:merge_data.primary_type.label}},
      yaxis: {title: {text:merge_data.secondary_type.label}},
      legend: {
        x: 0.1,
        y: 1.07
      },
      title: title,
    };
    Plotly.newPlot('pri_vs_sec', [offset, fit], layout2);

  </script>
  {% else %}
  <p>Please choose parameters to display plot</p>
  {% endif %}
</div>
{% endblock %}

d2qc/d2qc/data/templates/data/dataset_normalize.html
{% extends "base.html" %}
{% load mathfilters %}
{% block css %}
<link rel="stylesheet" type="text/css"
href="https://cdn.jsdelivr.net/gh/openlayers/openlayers.github.io@master/en/v5.3.0/css/ol.css">
<style>
    #diff_plot, #pri_vs_sec {
        height: 600px;
        width: 600px;
    }

    .outer {
      display: flex;
    }
    .normalizeform {
      display: flex;
      flex-wrap: wrap;
      width: 400px;
      justify-content: center;
    }
    .normalizebutton {
      width: 100%
    }
</style>
{% endblock %}
{% block js %}
{% endblock%}
{% block content %}
<h3>
  <a href="{% url 'data_set-detail' object.id %}">
    ID: {{ object.id }} - {{ object.expocode }}
  </a>
</h3>
<div class="outer">
  <form class="normalizeform" method="post">
    {% csrf_token %}
    <input class="normalizebutton" type="submit"
    value="Normalize selected parameters" name="normalize"/>
  </form>
</div>
{% endblock %}

d2qc/d2qc/data/templates/data/index.html
{% if links %}
    <ul>
    {% for link in links %}
        <li><a href="{{ link }}/">{{ link }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No crossovers available</p>
{% endif %}

d2qc/d2qc/data/templates/data/profile_form.html
{% extends "base.html" %}
{% block content %}
<h1>Crossover settings</h1>
    <form method="post">
        {% csrf_token %}
        {{ form.as_ul }}
        <input type="submit" value="Save" />
    </form>
{% endblock %}